
// This service stores character facts tagged by chapter.
// Only facts from read chapters are returned.

export interface CharacterFact {
  chapter: number;
  text: string;
}

export interface Character {
  name: string;
  facts: CharacterFact[];
}

// In a production app, this would be generated by NLP + indexing
const characterDatabase: Character[] = [
  {
    name: "Alice",
    facts: [
      { chapter: 1, text: "Alice is introduced as a curious girl." },
      { chapter: 5, text: "Alice meets the Caterpillar." },
      { chapter: 10, text: "Alice attends the trial." },
    ],
  },
];